### ISSUE TITLE
cannot retrieve sequences after installing muscle v.5 

### ISSUE THREAD

**Issue by fatipardo** [fatipardo/PDBClean-0.0.2#31]
When running Step0, trying to download the sequences from PDB, we get the following error:

Traceback (most recent call last):
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 1565, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 1586, in connect_ftp
    return ftpwrapper(user, passwd, host, port, dirs, timeout,
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 2407, in __init__
    self.init()
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 2416, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/ftplib.py", line 158, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fatima/Stanford/PDBClean/RIBOSOME/Step0.DownloadStructuralEnsembleFromRCSBPDB.py", line 85, in <module>
    ref_sequences, ref_metadata = pdbutils.retrieve_sequence_from_PDB(keyword, mode='metadata', update=True, seqfile=seqfile)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/PDBClean-0.0.2-py3.10.egg/PDBClean/pdbutils.py", line 60, in retrieve_sequence_from_PDB
    seqfile = retrieve_seqfile(seqfile=seqfile)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/PDBClean-0.0.2-py3.10.egg/PDBClean/pdbutils.py", line 89, in retrieve_seqfile
    download_from_url(sequrl, seqfile)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/PDBClean-0.0.2-py3.10.egg/PDBClean/pdbutils.py", line 96, in download_from_url
    with closing(urlopen(source)) as r:
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 1583, in ftp_open
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 1565, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 1586, in connect_ftp
    return ftpwrapper(user, passwd, host, port, dirs, timeout,
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 2407, in __init__
    self.init()
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/urllib/request.py", line 2416, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/ftplib.py", line 158, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
urllib.error.URLError: <urlopen error ftp error: ConnectionRefusedError(61, 'Connection refused')>

**Comment by fatipardo** [comment]
This error appeared after installing muscle v. 5 using conda. My guess is that some of the libraries were updated and that caused this to break. For now I fixed it by using the old kernel in jupyter notebook.

**Comment by fatipardo** [comment]
My guess was wrong. It seems to have been a problem with the remote server. I ran the code a couple of days later and the issue had resolved on its own.
