### ISSUE TITLE
When running "PDBClean_MolID_CIF.py" problem reading citation that uses multiple lines 

### ISSUE THREAD

**Issue by fatipardo** [fatipardo/PDBClean-0.0.2#35]
Traceback (most recent call last):
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/bin/PDBClean_MolID_CIF.py", line 4, in <module>
    __import__('pkg_resources').run_script('PDBClean==0.0.2', 'PDBClean_MolID_CIF.py')
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/PDBClean-0.0.2-py3.10.egg/EGG-INFO/scripts/PDBClean_MolID_CIF.py", line 32, in <module>
    master_molID_class_list = molidutils.pdb_to_masterlist(filelist)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/PDBClean-0.0.2-py3.10.egg/PDBClean/pdbcleanmolidcifutils.py", line 28, in pdb_to_masterlist
    this_molID_class = make_MolID_cif(myfile)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/PDBClean-0.0.2-py3.10.egg/PDBClean/pdbcleanmolidcifutils.py", line 182, in make_MolID_cif
    mmcif_dict = MMCIF2Dict(myfile)
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/Bio/PDB/MMCIF2Dict.py", line 37, in __init__
    for token in tokens:
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/Bio/PDB/MMCIF2Dict.py", line 126, in _tokenize
    yield from self._splitline(line.strip())
  File "/Users/fatima/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/Bio/PDB/MMCIF2Dict.py", line 102, in _splitline
    raise ValueError("Line ended with quote open: " + line)
ValueError: Line ended with quote open: 'Structural basis of the ribosomal machinery for Peptide bond formation,

**Comment by fatipardo** [comment]
This problem has already been addressed before and fixed here: https://github.com/fatipardo/PDBClean-0.0.2/issues/7#issuecomment-1204321310 

But somehow we reverted to an old version. So we are using the same fix again.

**Comment by fatipardo** [comment]
Notice that just as mentioned in #7 , we see this error when we run  PDBClean_MolID_CIF.py, but to fix, we need to re-run everything starting from the 'clean' step.
