### ISSUE TITLE
PDBChain Standardization Issue (first error message)

### ISSUE THREAD

**Issue by Liv-Weiner** [fatipardo/PDBClean-0.0.2#50]
Traceback (most recent call last):
  File "/Users/liv/opt/anaconda3/envs/PDBCleanV2/bin/PDBClean_ChainStandardization_CIF.py", line 4, in <module>
    __import__('pkg_resources').run_script('PDBClean==0.0.2', 'PDBClean_ChainStandardization_CIF.py')
  File "/Users/liv/opt/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script

    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/liv/opt/anaconda3/envs/PDBCleanV2/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1472, in run_script

**Comment by fatipardo** [comment]
We decided to rewrite this script, so many errors were fixed at once. This error does not shows up in the new version.
